
<br>
<?php 
// THIS HANDLES SETTING ERROR MESSAGES GENERATED BY SESSION

if (isset($_SESSION['err'])) {
        echo '
        <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
        <strong>Chyba!</strong> '.$_SESSION['err'].'
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                </button>
        </div>';
        $_SESSION['err'] = null;
}
?>